"""add candidate_memory and coach_plans

Revision ID: 094448535b1f
Revises: 6d395a53b032
Create Date: 2026-05-28 10:06:03.339885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '094448535b1f'
down_revision: Union[str, Sequence[str], None] = '6d395a53b032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_memory',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('latest_level', sa.String(length=20), nullable=True),
    sa.Column('cumulative_signals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('weakness_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_session_id', sa.UUID(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('coach_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consumed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coach_plans_user_unconsumed', 'coach_plans', ['user_id'], unique=False, postgresql_where=sa.text('consumed = false'))
    op.create_index(op.f('ix_coach_plans_user_id'), 'coach_plans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_plans_user_id'), table_name='coach_plans')
    op.drop_index('idx_coach_plans_user_unconsumed', table_name='coach_plans', postgresql_where=sa.text('consumed = false'))
    op.drop_table('coach_plans')
    op.drop_table('candidate_memory')
    # ### end Alembic commands ###
