"""add_user_qa_bank

Revision ID: 96e5708f0ff3
Revises: 3c7aa213fcb6
Create Date: 2026-06-01 10:35:18.531057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e5708f0ff3'
down_revision: Union[str, Sequence[str], None] = '3c7aa213fcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_qa_bank',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'hr', 'project')", name='ck_user_qa_bank_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_qa_bank_user_id'), 'user_qa_bank', ['user_id'], unique=False)
    op.add_column('interview_sessions', sa.Column('use_qa_bank', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'use_qa_bank')
    op.drop_index(op.f('ix_user_qa_bank_user_id'), table_name='user_qa_bank')
    op.drop_table('user_qa_bank')
    # ### end Alembic commands ###
