"""add_resume_fields

Revision ID: ca72dbc9da5b
Revises: 96e5708f0ff3
Create Date: 2026-06-01 11:46:57.244057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca72dbc9da5b'
down_revision: Union[str, Sequence[str], None] = '96e5708f0ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eval_comparisons_run_a_id'), table_name='eval_comparisons')
    op.drop_index(op.f('ix_eval_comparisons_run_b_id'), table_name='eval_comparisons')
    op.drop_index(op.f('ix_eval_results_case_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_runs_created_at'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_status'), table_name='eval_runs')
    op.drop_index(op.f('ix_eval_suites_name'), table_name='eval_suites')
    op.drop_index(op.f('ix_eval_suites_name_version'), table_name='eval_suites')
    op.add_column('users', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_filename')
    op.drop_column('users', 'resume_text')
    op.create_index(op.f('ix_eval_suites_name_version'), 'eval_suites', ['name', 'version'], unique=True)
    op.create_index(op.f('ix_eval_suites_name'), 'eval_suites', ['name'], unique=False)
    op.create_index(op.f('ix_eval_runs_status'), 'eval_runs', ['status'], unique=False)
    op.create_index(op.f('ix_eval_runs_created_at'), 'eval_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_eval_results_case_id'), 'eval_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_eval_comparisons_run_b_id'), 'eval_comparisons', ['run_b_id'], unique=False)
    op.create_index(op.f('ix_eval_comparisons_run_a_id'), 'eval_comparisons', ['run_a_id'], unique=False)
    # ### end Alembic commands ###
