"""add_resume_summary_to_users

Revision ID: e893374d74e3
Revises: 5bd19a28c7ea
Create Date: 2026-06-02 10:52:02.432358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e893374d74e3'
down_revision: Union[str, Sequence[str], None] = '5bd19a28c7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume_summary')
    # ### end Alembic commands ###
